In [2]:
import numpy as np

In [2]:
# Ejemplos clase 28 enero 2025
a = [1,2,3,4,5,7]

In [3]:
a

[1, 2, 3, 4, 5, 7]

In [5]:
c = 2*a
c
# Generará dos veces la lista

[1, 2, 3, 4, 5, 7, 1, 2, 3, 4, 5, 7]

In [6]:
d = [3,5,6,9,7,8]

In [7]:
e = a + d
e
# Concatena los vectores uno seguido del otro

[1, 2, 3, 4, 5, 7, 3, 5, 6, 9, 7, 8]

Numpy me permite hacer operaciones con los vectores porque los respeta como tal

In [3]:
# Ejercicios diapositivas
a = [1,3,5,7,9]
print(a[2:4])

[5, 7]


In [5]:
b = [[1,3,5,7,9],[2,4,6,8,10]]
print(b[0])

[1, 3, 5, 7, 9]


In [6]:
print(b[1][2:4])

[6, 8]


In [7]:
a = [1,3,5,7,9]
b = [3,5,6,7,9]
c = a + b
print(c)

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]


#### Para listas
* _np.array_

In [8]:
# para listas
## vectores
a = np.array ([1,3,5,7,9])
b = np.array ([3,5,6,7,9])
c = a + b
print(c)

[ 4  8 11 14 18]


In [9]:
type(c)

numpy.ndarray

In [10]:
c.shape

(5,)

In [12]:
# Matrices
l =[[1,2,3],[3,6,9],[2,4,6]]  # create a list
a = np.array(l) # convert a list to an array
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [13]:
a.shape

(3, 3)

In [14]:
print(a.dtype) # get type of an array

int64


In [15]:
# or directly as matrix
M = np.array([[1,2],[3,4]])
M.shape

(2, 2)

In [16]:
M.dtype

dtype('int64')

In [17]:
# only one type
M[0,0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

In [18]:
M = np.array([[1,2],[3,4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

### Matrices

In [19]:
# Uso de matrices
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [20]:
print(a[0]) # this is just like a list of lists

[1 2 3]


In [21]:
print(a[1,2]) # arrays can be given comma separated indices

9


In [23]:
print(a[1,1:3]) # and slices

[6 9]


In [24]:
print(a[:,1])

[2 6 4]


In [26]:
a[1,2] = 7 # cambia el valor de la posición 1,2
print(a)

[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [27]:
a[:, 0] = [0,9,8]
print(a)

[[0 2 3]
 [9 6 7]
 [8 4 6]]


### Arreglos

In [28]:
# Generation functions
x = np.arange(0, 10, 1) # arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [31]:
np.logspace(0, 10, 10, base = np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [32]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [33]:
b = np.zeros(5) # arreglos con cero como elemento
print(b)

[0. 0. 0. 0. 0.]


In [34]:
b.dtype

dtype('float64')

In [38]:
n = 1000
my_int_array = np.zeros(n, dtype = np.int32)
my_int_array.dtype

dtype('int32')

In [39]:
c = np.ones((3,3)) # Arreglos / matrices con elementos 1
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# Arreglos: Creación y uso
d = np.arange(5) # just like arange()
print(d)

[0 1 2 3 4]


In [41]:
d[1] = 9.7
print(d) # arrays keep their type even if elements changed

[0 9 2 3 4]


In [42]:
print(d*0.4) # operations create new array, with new type

[0.  3.6 0.8 1.2 1.6]


In [43]:
d = np.arange(5, dtype = np.float32)
print(d)

[0. 1. 2. 3. 4.]


In [44]:
np.arange(3, 7, 0.5) # arbitrary start, stop and step

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [45]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [46]:
# random data
np.random.rand(5, 5)

array([[0.74261195, 0.74390196, 0.08669274, 0.9906102 , 0.02844914],
       [0.42611632, 0.77652552, 0.8414573 , 0.02958656, 0.48061685],
       [0.11981596, 0.9000588 , 0.31130758, 0.82057234, 0.61996146],
       [0.30098606, 0.52414857, 0.2444536 , 0.76499886, 0.77687974],
       [0.11626271, 0.22866258, 0.26104524, 0.1391539 , 0.43522042]])

In [ ]:
# file I /O
os.system('head BeBilt.txt')
data = np.genfromtxt('Debilt.txt')  # lee los datos del archivo .txt
                                    # convierte el contenido del archivo en una estructura de datos de numpy
data.shape
np.savetxt('datasaved.txt', data)  # Guarda el nuevo arreglo en un archivo txt
os.system('head datasaved.txt')

# No se corrió la celda dado que no se contaba con el archivo txt

In [47]:
M = np.random.rand(3,3)
M

array([[0.40796183, 0.97535515, 0.59233519],
       [0.15067905, 0.64255633, 0.59896914],
       [0.93145818, 0.69976016, 0.62015688]])

In [49]:
np.save('saved-matrix.npy', M)
np.load('saved-matrix.npy')

array([[0.40796183, 0.97535515, 0.59233519],
       [0.15067905, 0.64255633, 0.59896914],
       [0.93145818, 0.69976016, 0.62015688]])