In [2]:
import numpy as np

In [2]:
# Ejemplos clase 28 enero 2025
a = [1,2,3,4,5,7]

In [3]:
a

[1, 2, 3, 4, 5, 7]

In [5]:
c = 2*a
c
# Generará dos veces la lista

[1, 2, 3, 4, 5, 7, 1, 2, 3, 4, 5, 7]

In [6]:
d = [3,5,6,9,7,8]

In [7]:
e = a + d
e
# Concatena los vectores uno seguido del otro

[1, 2, 3, 4, 5, 7, 3, 5, 6, 9, 7, 8]

Numpy me permite hacer operaciones con los vectores porque los respeta como tal

In [3]:
# Ejercicios diapositivas
a = [1,3,5,7,9]
print(a[2:4])

[5, 7]


In [5]:
b = [[1,3,5,7,9],[2,4,6,8,10]]
print(b[0])

[1, 3, 5, 7, 9]


In [6]:
print(b[1][2:4])

[6, 8]


In [7]:
a = [1,3,5,7,9]
b = [3,5,6,7,9]
c = a + b
print(c)

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]


#### Para listas
* _np.array_

In [8]:
# para listas
## vectores
a = np.array ([1,3,5,7,9])
b = np.array ([3,5,6,7,9])
c = a + b
print(c)

[ 4  8 11 14 18]


In [9]:
type(c)

numpy.ndarray

In [10]:
c.shape

(5,)

In [12]:
# Matrices
l =[[1,2,3],[3,6,9],[2,4,6]]  # create a list
a = np.array(l) # convert a list to an array
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [13]:
a.shape

(3, 3)

In [14]:
print(a.dtype) # get type of an array

int64


In [15]:
# or directly as matrix
M = np.array([[1,2],[3,4]])
M.shape

(2, 2)

In [16]:
M.dtype

dtype('int64')

In [17]:
# only one type
M[0,0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

In [18]:
M = np.array([[1,2],[3,4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

### Matrices

In [19]:
# Uso de matrices
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [20]:
print(a[0]) # this is just like a list of lists

[1 2 3]


In [21]:
print(a[1,2]) # arrays can be given comma separated indices

9


In [23]:
print(a[1,1:3]) # and slices

[6 9]


In [24]:
print(a[:,1])

[2 6 4]


In [26]:
a[1,2] = 7 # cambia el valor de la posición 1,2
print(a)

[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [27]:
a[:, 0] = [0,9,8]
print(a)

[[0 2 3]
 [9 6 7]
 [8 4 6]]


### Arreglos

In [28]:
# Generation functions
x = np.arange(0, 10, 1) # arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [31]:
np.logspace(0, 10, 10, base = np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [32]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [33]:
b = np.zeros(5) # arreglos con cero como elemento
print(b)

[0. 0. 0. 0. 0.]


In [34]:
b.dtype

dtype('float64')

In [38]:
n = 1000
my_int_array = np.zeros(n, dtype = np.int32)
my_int_array.dtype

dtype('int32')

In [39]:
c = np.ones((3,3)) # Arreglos / matrices con elementos 1
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Arreglos: Creación y uso